### ISSUE TITLE
getpixelcolor() 

### ISSUE THREAD

**Issue by Szetya** [Xylopyrographer/LiteLED#3]
A very nice and simple library. I am glad I found it. In the future, it might be useful to have a getpixelcolor() that returns the current color code of the given LED.

**Comment by Xylopyrographer** [comment]
Hi. Glad you found it useful.

Should be able to implement a method like that. I've been watching progress on version 3 of the arduino-esp32 core, looking to time the next release with that as it will break LiteLED due to a complete rewrite by Espressif of the RMT implementation.

In the mean time: could you let me know which LED type(s) you use with LiteLED and roughly the number of LED's. Curious about how the library is being used.

**Comment by Xylopyrographer** [comment]
Wasn't too hard to add. See new Release v1.1.0

Let me know how it works out for you.
