### ISSUE TITLE
LiteLED issue with SK6812 and Xiao ESP32C3

### ISSUE THREAD

**Issue by oehoe** [Xylopyrographer/LiteLED#6]
I'm trying to drive a 81 LED's long SK6812 strip with LiteLED. With Adafruit neopixel library no issues but with LiteLED 1.2.0 random LED's light up with random colors.

I'm using the following code. See [YouTube](https://youtu.be/tfFTl7urYFU) for result.

```
#include <LiteLED.h>

#define LED_TYPE        LED_STRIP_SK6812
#define LED_TYPE_IS_RGBW 0   // if the LED is an RGBW type, change the 0 to 1
#define LED_PIN 4     // change this number to be the GPIO pin connected to the LED
#define NUMPIXELS 81

LiteLED myLED( LED_TYPE, LED_TYPE_IS_RGBW, RMT_CHANNEL_0 );

void setup() {
    myLED.begin( LED_PIN, NUMPIXELS );
    myLED.brightness( 255 );
}

void loop() {
  myLED.clear(1);
  for (int a = 0; a < NUMPIXELS; a++) {
    rgb_t myColour = { .r = 0, .g = 40, .b = 0 };
    myLED.setPixel( a, myColour );
    myLED.show();
    delay(200);
  }
} 
```

**Comment by Xylopyrographer** [comment]
Hi. Thanks for the info. That's an "interesting" result.

I ran your code on an M5Stack ATOM MATRIX & it  worked as expected (25 pixels of WS2812 type in a row-by-row matrix).

I'd have to dig around to duplicate your setup with the Xiao ESP32C3.

In the mean time,  could you post:
- the OS of your computer
- the Arduino IDE version
- the version of the Arduino-esp32 core being used.

Did you try power cycling the setup before uploading the LiteLED code?

**Comment by oehoe** [comment]
Thanks for your reply.
- Mac OS Sonoma on an M2 MacBook Air
- Arduino IDE 2.3.2
- I had to install version 2.0.11 of the esp32 boards because LiteLED requires version below 3.0.0.
- Power cycling before uploading did not help.

**Comment by Xylopyrographer** [comment]
OK.

Two things to try:

1. Add the line:
`  delay( 200 );`
after 
`  myLED.clear(1);`
so the code would be:
```
#include <LiteLED.h>

#define LED_TYPE        LED_STRIP_SK6812
#define LED_TYPE_IS_RGBW 0   // if the LED is an RGBW type, change the 0 to 1
#define LED_PIN 4     // change this number to be the GPIO pin connected to the LED
#define NUMPIXELS 81

LiteLED myLED( LED_TYPE, LED_TYPE_IS_RGBW, RMT_CHANNEL_0 );

void setup() {
    myLED.begin( LED_PIN, NUMPIXELS );
    myLED.brightness( 255 );
}

void loop() {
  myLED.clear(1);
  delay( 200 );
  for (int a = 0; a < NUMPIXELS; a++) {
    rgb_t myColour = { .r = 0, .g = 40, .b = 0 };
    myLED.setPixel( a, myColour );
    myLED.show();
    delay(200);
  }
} 
```
2. If that doesn't work, upgrade the arduino-esp32 core to v2.0.14 & try again. (Don't use core v2.0.15 - it is unstable.)

If it still doesn't work, I can try and replicate your setup - but that'll take a bit of time.

**Comment by Xylopyrographer** [comment]
@oehoe 

Ran through a series of tests.

Configuration:
XIAO ESP32C3
8 by 8 RGB LED panel , serpentine ordered, using WS2812 RGB LEDs ( I don't have an SK6812 panel.)
Separate 5V supply for the LED panel
100 ohm resistor between the data line and the DIN pin of the panel
Panel DIN driven via a level shifter from the XIAO.

With that setup and Arduino IDE settings of:

Board: "XIAO_ESP32C3"
Port: "your/board/port"
USB CDC On Boot: "Enabled"
CPU Frequency: "160MHZ (WiFi)"
Core Debug Level: "None"
Erase All Flash Before Sketch Upload: "Disabled"
Flash Frequency: "80MHz"
Flash Mode: "DIO"
Flash Size: "4MB (32Mb)"
Partition Scheme: "Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS)"
Upload Speed: "921600"
Programmer: "Esptool"

Your original code above worked as expected.

I even reduced the `delay(200)`  line to  `delay(0)` and it worked.

It also worked when setting CPU Frequency: "80MHz (WiFi)".

Likewise, with the CPU frequency at 160 MHz or 80 MHz and Flash Frequency: "40MHZ" it worked.

However, if I set the CPU frequency to any one of 40MHz, 20MHz or 10MHz, regardless of the Flash Frequency setting, it would fail.

Though in my case the failure mode was all LEDs illuminated at full brightness with r, g, b values of 255 each. I did not get the random patterns you demonstrated. That may be due to timing differences between the SK6812 and WS2812 LEDs.

So, assuming power consumption of the XIAO isn't a concern in your system, setting the CPU frequency either 80 or 160 MHz should resolve the issue. If not, try defining the panel as a different type.

FWIW, I also ran the tests defining the LED count as 81. Results were the same except of course there was an apparent delay as the extra data was being pushed to the non-existent LEDs.

Let me know how it goes.
